version: '3.1'

services:
  chogan:
    restart: always
    build:
      context: .
    stdin_open: true
    tty: true
    volumes:
      - .:/chogan/
    ports:
      - "1111:8000"

  redis:
    image: redis
